### ISSUE TITLE
Couldn't do Android build with Tealium v1.1.1

### ISSUE THREAD

**Issue by rajeshnarayanan-mcoe** [Tealium/tealium-android#45]
I m getting the following error while building Android platform with the new version of tealium plugin.
We are using cordova version: 8.0.0
Android: 6.4.0

BUILD FAILED in 4s
38 actionable tasks: 36 executed, 2 up-to-date
(node:14911) UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 1): Error: /Users/rajeshna/Documents/ieee-moce-development/my-xplore/platforms/android/gradlew: Command failed with exit code 1 Error output:
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
/Users/rajeshna/Documents/ieee-moce-development/my-xplore/platforms/android/src/org/apache/cordova/plugin/TealiumPg.java:121: error: diamond operator is not supported in -source 1.6
            ArrayList<String> moduleErrors = new ArrayList<>(3);
                                                                                                ^

**Comment by craigrouse** [comment]
@rajeshnarayanan-mcoe I think you have opened an issue on the wrong repo. Please see: https://github.com/Tealium/cordova-plugin/issues/31

Closing this issue as a duplicate.
